blank_issues_enabled: false
contact_links:
  - name: clashauto Community Support
    url: https://github.com/ClashrAuto/clash/discussions
    about: Please ask and answer questions about clashauto here.
